export const ChallengeStatuses = {
  New: 'NEW',
  Active: 'ACTIVE',
  Draft: 'DRAFT',
  Approved: 'APPROVED',
  Canceled: 'CANCELLED',
  Completed: 'COMPLETED',
  Deleted: 'DELETED',
  CancelledFailedReview: 'CANCELLED_FAILED_REVIEW',
  CancelledFailedScreening: 'CANCELLED_FAILED_SCREENING',
  CancelledZeroSubmissions: 'CANCELLED_ZERO_SUBMISSIONS',
  CancelledWinnerUnresponsive: 'CANCELLED_WINNER_UNRESPONSIVE',
  CancelledClientRequest: 'CANCELLED_CLIENT_REQUEST',
  CancelledRequirementsInfeasible: 'CANCELLED_REQUIREMENTS_INFEASIBLE',
  CancelledZeroRegistrations: 'CANCELLED_ZERO_REGISTRATIONS',
  CancelledPaymentFailed: 'CANCELLED_PAYMENT_FAILED',
};
