export const ChallengeStatuses = {
  New: "New",
  Active: "Active",
  Draft: "Draft",
  Approved: "Approved",
  Canceled: "Canceled",
  Completed: "Completed",
  Deleted: "Deleted",
  CancelledFailedReview: "Cancelled - Failed Review",
  CancelledFailedScreening: "Cancelled - Failed Screening",
  CancelledZeroSubmissions: "Cancelled - Zero Submissions",
  CancelledWinnerUnresponsive: "Cancelled - Winner Unresponsive",
  CancelledClientRequest: "Cancelled - Client Request",
  CancelledRequirementsInfeasible: "Cancelled - Requirements Infeasible",
  CancelledZeroRegistrations: "Cancelled - Zero Registrations",
  CancelledPaymentFailed: "Cancelled - Payment Failed",
};
